version: 3
tasks:
  - name: Install dependencies
    command: pip install -r requirements.txt

  - name: Run tests
    command: python manage.py test

  - name: Collect static
    command: python manage.py collectstatic

  - name: Deploy application
    command: pa_autoconfigure_django.py --python=3.7 ajeshvyas.pythonanywhere.com
